{
 "title": "Skincare Chatbot Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Relevance Distribution Panel",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "select feedback, count(*)\nfrom feedback\ngroup by 1"
    }
   ]
  },
  {
   "title": "OpenAI Cost Panel",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(timestamp, $__interval) AS time,\n  SUM(openai_cost) AS total_cost\nFROM conversations\nWHERE timestamp BETWEEN $__timeFrom() AND $__timeTo()\n  AND openai_cost > 0\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Recent Conversations Panel",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS time,\n  question,\n  answer\nFROM conversations\nWHERE timestamp BETWEEN $__timeFrom() AND $__timeTo()\nORDER BY timestamp DESC\nLIMIT 5"
    }
   ]
  },
  {
   "title": "Feedback Statistics Panel",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \nCOALESCE(SUM(CASE WHEN feedback = 'RELEVANT' THEN 1 ELSE 0 END), 0) as thumbs_up,\nCOALESCE(SUM(CASE WHEN feedback = 'NON_RELEVANT' THEN 1 ELSE 0 END), 0) as thumbs_down\nFROM feedback\nWHERE created_at BETWEEN $__timeFrom() AND $__timeTo()"
    }
   ]
  },
  {
   "title": "Token Usage Panel",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(timestamp, $__interval) AS time,\n  AVG(total_tokens) AS avg_tokens\nFROM conversations\nWHERE timestamp BETWEEN $__timeFrom() AND $__timeTo()\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Response Time Panel",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS time,\n  response_time\nFROM conversations\nWHERE timestamp BETWEEN $__timeFrom() AND $__timeTo()\nORDER BY timestamp"
    },
    {
     "rawSql": "SELECT\n  timestamp AS time,\n  question,\n  answer,\n  relevance\nFROM conversations\nORDER BY timestamp DESC\nLIMIT 5"
    }
   ]
  }
 ]
}